app = "asistente-humano"

primary_region = "scl"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services.ports]]
  handlers = ["http"]
  port = 8080


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
