app = "asistente-backend" # Cambia esto por el nombre de tu aplicación en Fly.io

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080" # Asegúrate de que coincida con el puerto que usa tu backend

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443